[package]
name = "tokio-timerfd"
version = "0.1.0"
authors = ["Alexander Polakov <a.polakov@iconic.vc>"]
edition = "2018"

[dependencies]
tokio-reactor = "0.1"
mio = "0.6"
timerfd = "1.0"
futures = "0.1"

[dev-dependencies]
tokio = "0.1"
