[package]
name = "tokio-timerfd"
version = "0.1.0"
authors = ["Alexander Polakov <a.polakov@iconic.vc>"]
edition = "2018"
description = "timerfd support for tokio"
license = "MIT"
documentation = "https://docs.rs/tokio-timerfd"
repository = "https://github.com/polachok/tokio-timerfd"
homepage = "https://github.com/polachok/tokio-timerfd"

[dependencies]
tokio-reactor = { git = "https://github.com/polachok/tokio", rev = "58f087" }
tokio-timer = { git = "https://github.com/polachok/tokio", rev = "58f087" }
tokio-executor = { git = "https://github.com/polachok/tokio", rev = "58f087" }
mio = "0.6"
timerfd = "1.0"
futures = "0.1"

[dev-dependencies]
tokio = { git = "https://github.com/polachok/tokio", rev = "58f087" }
